import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
file=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\SuperStoreOrders.csv")
script_dir=os.path.dirname(os.path.abspath(__file__))
save=os.path.join(script_dir,"Graphs and Charts")
if not os.path.exists(save):os.makedirs(save)
def Data_Assessment():
    print(file.head())
    print(file.size)
    print(file.dtypes)
    print(file.isnull().sum())      #No Null Values Found.
    print(file[file.duplicated()])  #No Duplicate Values Found.
def Sales_Analysis():
    file["sales"] = file["sales"].astype(str).str.replace(",", "")
    file["sales"] = pd.to_numeric(file["sales"], errors="coerce")
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    filtred1=file.groupby("category")["sales"].sum().sort_values(ascending=False).index.tolist()
    pdcat=file[file["category"].isin(filtred1)].groupby(["category","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdcat,x="category",y="sales",hue="year",palette="viridis")
    plt.xlabel("Category")
    plt.ylabel("Total Revenue Generated In Millions")
    plt.legend(title="Fiscal Year")
    plt.title("Category Performance")
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    filtred=file.groupby("sub_category")["sales"].sum().sort_values(ascending=False).index.tolist()
    pds=file[file["sub_category"].isin(filtred)].groupby(["sub_category","year"])["sales"].sum().reset_index()
    sns.barplot(data=pds,y="sub_category",x="sales",hue="year",palette="viridis")
    plt.ylabel("Sub-Category")
    plt.xlabel("Total Revenue Generated")
    plt.legend(title="Fiscal Year")
    plt.title("Sub-Category Performance")
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    top10=file.groupby("product_name")["sales"].sum().sort_values(ascending=False).head(10).index.tolist()
    pdp=file[file["product_name"].isin(top10)].groupby(["product_name","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdp,y="product_name",x="sales",hue="year",order=top10,palette="viridis")
    plt.xlabel("Total Revenue Generated")
    plt.ylabel("Product Name")
    plt.legend(title="Fiscal Year")
    plt.title("Top 10 Product Performance")
    plt.tight_layout()
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    top10c=file.groupby("country")["sales"].sum().sort_values(ascending=False).head(10).index.tolist()
    pdc=file[file["country"].isin(top10c)].groupby(["country","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdc,y="country",x="sales",hue="year",order=top10c,palette="viridis")
    plt.xlabel("Total Revenue Generated")
    plt.ylabel("Country")
    plt.title("Top 10 Countries With Highest Revenue")
    plt.legend(title="Fiscal Year")
    plt.show()
def Profit_Analysis():
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    f1=file.groupby("category")["profit"].sum().sort_values(ascending=False).index.tolist()
    pdcat=file[file["category"].isin(f1)].groupby(["category","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,x="category",y="profit",hue="year",palette="viridis")
    plt.xlabel("Category")
    plt.ylabel("Profit")
    plt.title("Categories And Profit")
    plt.legend(title="Fiscal Year")
    plt.show()
    f2=file.groupby("product_name")["profit"].sum().sort_values(ascending=False).head(5).index.tolist()
    pdcat=file[file["product_name"].isin(f2)].groupby(["product_name","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,y="product_name",x="profit",hue="year",palette="viridis")
    plt.ylabel("Product")
    plt.xlabel("Profit")
    plt.title("TOP 5 Profitable Products")
    plt.legend(title="Fiscal Year")
    plt.tight_layout()
    plt.show()
    f3=file.groupby("product_name")["profit"].sum().sort_values(ascending=True).head(5).index.tolist()
    pdcat=file[file["product_name"].isin(f3)].groupby(["product_name","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,y="product_name",x="profit",hue="year",palette="viridis")
    plt.ylabel("Product")
    plt.xlabel("Profit")
    plt.title("TOP 5 Least Profitable Products")
    plt.legend(title="Fiscal Year")
    plt.tight_layout()
    plt.show()
    f4=file.groupby("region")["profit"].sum().sort_values(ascending=True).index.tolist()
    pdcat=file[file["region"].isin(f4)].groupby(["region","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,y="region",x="profit",hue="year",palette="viridis")
    plt.ylabel("Region")
    plt.xlabel("Profit")
    plt.title("Region And Profit")
    plt.legend(title="Fiscal Year")
    plt.show()
    f5=file.groupby("market")["profit"].sum().sort_values(ascending=True).index.tolist()
    pdcat=file[file["market"].isin(f5)].groupby(["market","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,y="market",x="profit",hue="year",palette="viridis")
    plt.ylabel("Market")
    plt.xlabel("Profit")
    plt.title("Market And Profit")
    plt.legend(title="Fiscal Year")
    plt.show()
Data_Assessment()
Sales_Analysis()
Profit_Analysis()