import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
file=pd.read_csv(r"C:\Users\shiva\OneDrive\Desktop\SuperStoreOrders.csv")
script_dir=os.path.dirname(os.path.abspath(__file__))
save=os.path.join(script_dir,"Graphs and Charts")
if not os.path.exists(save):os.makedirs(save)
file["sales"] = file["sales"].astype(str).str.replace(",", "")
file["sales"] = pd.to_numeric(file["sales"], errors="coerce")      #It is to clean sales data for better analysis.
file["month_year"] = file["order_date"].str[-7:]                   #This handles both '/' and '-' formats
def Data_Assessment():
    print(file.head())
    print(file.size)
    print(file.dtypes)
    print(file.isnull().sum())      #No Null Values Found.
    print(file[file.duplicated()])  #No Duplicate Values Found.
def Sales_Analysis():
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    filtred1=file.groupby("category")["sales"].sum().sort_values(ascending=False).index.tolist()
    pdcat=file[file["category"].isin(filtred1)].groupby(["category","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdcat,x="category",y="sales",hue="year",palette="viridis")
    plt.xlabel("Category")
    plt.ylabel("Total Revenue Generated In Millions")
    plt.legend(title="Fiscal Year")
    plt.title("Category Performance")
    plt.savefig(os.path.join(save,"Category_Performance.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    filtred9=file.groupby("segment")["sales"].sum().sort_values(ascending=False).index.tolist()
    pdcat=file[file["segment"].isin(filtred9)].groupby(["segment","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdcat,x="segment",y="sales",hue="year",palette="viridis")
    plt.xlabel("Segment")
    plt.ylabel("Total Revenue Generated In Millions")
    plt.legend(title="Fiscal Year")
    plt.title("Segment Performance")
    plt.savefig(os.path.join(save,"Segment_Performance.png"),dpi=300)
    plt.show()
    f8=file.groupby("order_priority")["sales"].sum().sort_values(ascending=False).index.tolist()
    pdcat=file[file["order_priority"].isin(f8)].groupby(["order_priority","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdcat,x="order_priority",y="sales",hue="year",palette="viridis")
    plt.xlabel("Order Priority")
    plt.ylabel("Revenue Generated In Millions")
    plt.title("Order Priority And Revenue")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Order_Priority_And_Revenue.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    filtred=file.groupby("sub_category")["sales"].sum().sort_values(ascending=False).index.tolist()
    pds=file[file["sub_category"].isin(filtred)].groupby(["sub_category","year"])["sales"].sum().reset_index()
    sns.barplot(data=pds,y="sub_category",x="sales",hue="year",palette="viridis")
    plt.ylabel("Sub-Category")
    plt.xlabel("Total Revenue Generated")
    plt.legend(title="Fiscal Year")
    plt.title("Sub-Category Performance")
    plt.savefig(os.path.join(save,"Sub_Category_Performance.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    top10=file.groupby("product_name")["sales"].sum().sort_values(ascending=False).head(10).index.tolist()
    pdp=file[file["product_name"].isin(top10)].groupby(["product_name","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdp,y="product_name",x="sales",hue="year",order=top10,palette="viridis")
    plt.xlabel("Total Revenue Generated")
    plt.ylabel("Product Name")
    plt.legend(title="Fiscal Year")
    plt.title("Top 10 Product Performance")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Top_10_Product_Performance.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    top10c=file.groupby("country")["sales"].sum().sort_values(ascending=False).head(10).index.tolist()
    pdc=file[file["country"].isin(top10c)].groupby(["country","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdc,y="country",x="sales",hue="year",order=top10c,palette="viridis")
    plt.xlabel("Total Revenue Generated")
    plt.ylabel("Country")
    plt.title("Top 10 Countries With Highest Revenue")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Top_10_Country.png"),dpi=300)
    plt.show()
    f4=file.groupby("region")["sales"].sum().sort_values(ascending=True).index.tolist()
    pdr=file[file["region"].isin(f4)].groupby(["region","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdr,y="region",x="sales",hue="year",palette="viridis")
    plt.ylabel("Region")
    plt.xlabel("Total Revenue Generated")
    plt.title("Region And Revenue")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Region_Revenue.png"),dpi=300)
    plt.show()
    f5=file.groupby("market")["sales"].sum().sort_values(ascending=True).index.tolist()
    pdm=file[file["market"].isin(f5)].groupby(["market","year"])["sales"].sum().reset_index()
    sns.barplot(data=pdm,y="market",x="sales",hue="year",palette="viridis")
    plt.ylabel("Market")
    plt.xlabel("Total Revenue Generated")
    plt.title("Market And Revenue")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Market_Revenue.png"),dpi=300)
    plt.show()
def Profit_Analysis():
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    f1=file.groupby("category")["profit"].sum().sort_values(ascending=False).index.tolist()
    pdcat=file[file["category"].isin(f1)].groupby(["category","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,x="category",y="profit",hue="year",palette="viridis")
    plt.xlabel("Category")
    plt.ylabel("Profit")
    plt.title("Categories And Profit")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Category_Profit.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    f9=file.groupby("segment")["profit"].sum().sort_values(ascending=False).index.tolist()
    pdcat=file[file["segment"].isin(f9)].groupby(["segment","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,x="segment",y="profit",hue="year",palette="viridis")
    plt.xlabel("Segment")
    plt.ylabel("Profit")
    plt.title("Segment And Profit")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Segment_Profit.png"),dpi=300)
    plt.show()
    f8=file.groupby("order_priority")["profit"].sum().sort_values(ascending=False).index.tolist()
    pdcat=file[file["order_priority"].isin(f8)].groupby(["order_priority","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,x="order_priority",y="profit",hue="year",palette="viridis")
    plt.xlabel("Order Priority")
    plt.ylabel("Profit")
    plt.title("Order Priority And Profit")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Order_Priority_Profit.png"),dpi=300)
    plt.show()
    f2=file.groupby("product_name")["profit"].sum().sort_values(ascending=False).head(5).index.tolist()
    pdcat=file[file["product_name"].isin(f2)].groupby(["product_name","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,y="product_name",x="profit",hue="year",palette="viridis")
    plt.ylabel("Product")
    plt.xlabel("Profit")
    plt.title("TOP 5 Profitable Products")
    plt.legend(title="Fiscal Year")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Top_5_Product_Profit.png"),dpi=300)
    plt.show()
    f3=file.groupby("product_name")["profit"].sum().sort_values(ascending=True).head(5).index.tolist()
    pdcat=file[file["product_name"].isin(f3)].groupby(["product_name","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,y="product_name",x="profit",hue="year",palette="viridis")
    plt.ylabel("Product")
    plt.xlabel("Profit")
    plt.title("TOP 5 Least Profitable Products")
    plt.legend(title="Fiscal Year")
    plt.tight_layout()
    plt.savefig(os.path.join(save,"Top_5_least_profit_product.png"),dpi=300)
    plt.show()
    f4=file.groupby("region")["profit"].sum().sort_values(ascending=True).index.tolist()
    pdcat=file[file["region"].isin(f4)].groupby(["region","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,y="region",x="profit",hue="year",palette="viridis")
    plt.ylabel("Region")
    plt.xlabel("Profit")
    plt.title("Region And Profit")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Region_profit.png"),dpi=300)
    plt.show()
    f5=file.groupby("market")["profit"].sum().sort_values(ascending=True).index.tolist()
    pdcat=file[file["market"].isin(f5)].groupby(["market","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,y="market",x="profit",hue="year",palette="viridis")
    plt.ylabel("Market")
    plt.xlabel("Profit")
    plt.title("Market And Profit")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Market_profit.png"),dpi=300)
    plt.show()
    f7=file.groupby("discount")["profit"].sum().sort_values(ascending=True).index.tolist()
    pdcat=file[file["discount"].isin(f7)].groupby(["discount","year"])["profit"].sum().reset_index()
    sns.barplot(data=pdcat,x="discount",y="profit",hue="year",palette="viridis")
    plt.xlabel("Discount")
    plt.ylabel("Profit")
    plt.title("Discount And Profit")
    plt.legend(title="Fiscal Year")
    plt.savefig(os.path.join(save,"Discount_profit.png"),dpi=300)
    plt.show()
def Customer_Analysis():
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    f1=file.groupby("customer_name")["sales"].sum().sort_values(ascending=False).head(10).index.tolist()
    pdcat=file[file["customer_name"].isin(f1)].groupby(["customer_name","category"])["sales"].sum().reset_index()
    sns.barplot(data=pdcat,y="customer_name",x="sales",hue="category",order=f1,palette="viridis")
    plt.ylabel("Customer")
    plt.xlabel("Revenue Contributed")
    plt.title("Top 10 Customers And Categories")
    plt.legend(title="Category")
    plt.savefig(os.path.join(save,"Customer_Category.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    f2=file.groupby("customer_name")["sales"].sum().sort_values(ascending=False).head(10).index.tolist()
    pdcat=file[file["customer_name"].isin(f2)].groupby(["customer_name","segment"])["sales"].sum().reset_index()
    sns.barplot(data=pdcat,y="customer_name",x="sales",hue="segment",order=f2,palette="viridis")
    plt.ylabel("Customer")
    plt.xlabel("Revenue Contributed")
    plt.title("Top 10 Customers And Segment")
    plt.legend(title="Segment")
    plt.savefig(os.path.join(save,"Customer_Segment.png"),dpi=300)
    plt.show()
def Time_Based_Analysis():
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    lock=file["year"].value_counts().index
    sns.countplot(data=file[file["year"].isin(lock)],x="year",hue="category",order=lock,palette="viridis",legend=True)
    plt.title("Year And No. Of Orders")
    plt.xlabel("Fiscal Year")
    plt.ylabel("No.Of orders")
    plt.legend(title="Category")
    plt.savefig(os.path.join(save,"Year_No._Of_Orders.png"),dpi=300)
    plt.show()
    plt.figure(figsize=(10,8))
    sns.set_style("whitegrid")
    top5m = (file.groupby(["month_year","year"])["profit"].sum().sort_values(ascending=False).head(5).reset_index())
    sns.barplot(data=top5m,x="month_year",y="profit",hue="year",order=top5m["month_year"],palette="viridis")
    plt.xlabel("Month")
    plt.ylabel("Total Profit Gained")
    plt.title("Top 5 Most Profitable Months")
    plt.legend(title="year")
    plt.savefig(os.path.join(save,"Profit_Month.png"),dpi=300)
    plt.show()
    top5md = (file.groupby(["month_year","year"])["profit"].sum().sort_values(ascending=True).head(5).reset_index())
    sns.barplot(data=top5md,x="month_year",y="profit",hue="year",order=top5md["month_year"],palette="magma")
    plt.xlabel("Month")
    plt.ylabel("Total Profit Gained")
    plt.title("5 Least Profitable Months")
    plt.legend(title="year")
    plt.savefig(os.path.join(save,"Least_Profit_Month.png"),dpi=300)
    plt.show()
def Shipping_Analysis():
    plt.show()
    f3=file.groupby("market")["shipping_cost"].sum().sort_values(ascending=False).index.tolist()
    pdy=file[file["market"].isin(f3)].groupby(["market","ship_mode"])["shipping_cost"].sum().reset_index()
    sns.barplot(data=pdy,x="market",y="shipping_cost",hue="ship_mode",order=f3,palette="viridis")
    plt.xlabel("Market")
    plt.ylabel("Shipping Cost")
    plt.title("Market And Shipping Cost")
    plt.legend(title="Ship Mode")
    plt.savefig(os.path.join(save,"Market_shipping_cost.png"),dpi=300)
    plt.show()
Data_Assessment()
Sales_Analysis()
Profit_Analysis()
Customer_Analysis()
Time_Based_Analysis()
Shipping_Analysis()